# Generated by Django 4.0.5 on 2022-06-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupant_name', models.CharField(default='', max_length=200)),
                ('occupant_address', models.CharField(default='', max_length=200)),
                ('occupant_email', models.EmailField(default='', max_length=254)),
                ('occupant_occupation', models.CharField(default='', max_length=200)),
                ('room_number', models.IntegerField(default=1)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_night', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
