# Generated by Django 4.0.5 on 2022-06-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_hotelrecord_number_of_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelrecord',
            name='number_of_night',
        ),
    ]
