# Generated by Django 4.0.5 on 2022-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_occupantdetails_occupantdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelrecord',
            name='occupant',
        ),
        migrations.AddField(
            model_name='hotelrecord',
            name='occupant_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelrecord',
            name='occupant_age',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='hotelrecord',
            name='occupant_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='hotelrecord',
            name='occupant_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelrecord',
            name='occupant_occupation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hotelrecord',
            name='number_of_night',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='hotelrecord',
            name='room_number',
            field=models.IntegerField(default=''),
        ),
        migrations.DeleteModel(
            name='OccupantDetail',
        ),
    ]
