# Generated by Django 4.0.5 on 2022-06-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_hotelrecord_occupant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrecord',
            name='number_of_night',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hotelrecord',
            name='occupant_age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hotelrecord',
            name='room_number',
            field=models.IntegerField(default=1),
        ),
    ]
