# Generated by Django 4.0.5 on 2022-06-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_hotelrecord_number_of_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrecord',
            name='occupant_age',
            field=models.IntegerField(default=23),
        ),
    ]
