# Generated by Django 4.0.5 on 2022-06-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_hotelrecord_occupant_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelrecord',
            name='occupant_age',
        ),
    ]
