# Generated by Django 4.0.5 on 2022-06-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_hotelrecord_occupant_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelRecord',
        ),
    ]
